name: Report to packtracker.io
on: [push]
jobs:
  build:
    name: report
    runs-on: ubuntu-latest
    steps:
      - name: Run next.js build
        uses: node:12-slim
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
        run: |
          yarn
          yarn build
